### ISSUE TITLE
Retry when Channel is Closed

### ISSUE THREAD

**Issue by ovu** [reactor/reactor-rabbitmq#131]
Hi there,

I am having issues when reactor-rabbitmq when the connection to Rabbit is closed, e.g when network is not available for some reason.

I found in the documentation that there is a way to configure a retry mechanismus with exponential backoff when the application is starting (https://projectreactor.io/docs/rabbitmq/milestone/reference/), however there is no way to retry when the channel is closed? 

When the network is gone, I just see the following lines in the logs:
reactor.rabbitmq.RabbitFluxException: Not retryable exception, cannot retry
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown;

Thanks for your help!

**Comment by acogoluegnes** [comment]
There are sections in the documentation about retry for publishing and consuming:
https://projectreactor.io/docs/rabbitmq/milestone/reference/#_error_handling_during_publishing
https://projectreactor.io/docs/rabbitmq/milestone/reference/#_connection_failure

You should get familiar with this. The default retry mechanism may not be suited to your problem and you may need to tweak it.

It's hard to tell with the exception you provided if it's really a network problem though. I would also look into the server logs to make sure it's a network problem before changing the default retry mechanism.

**Comment by ovu** [comment]
Hi @acogoluegnes,

thanks for your answer. I will review the documentation.

I supposed the error was because of a network problem because I am using MongoDB as well an Mongo reporter a socket exception. However, in the logs the only line before the Exception that I see in the logs is:

reactor.rabbitmq.Receiver                : Cancelling consumer amq.ctag-amG3C0CP6YImGAilPUPA_w consuming from export.elements

After that I just saw the exceptions I posted before. What else can cause that the Receiver cancells the consumer? 

By the way, from my logs I can see that the reactor-mongodb tried to reconnect and after 2 seconds it succeeded. However RabbitMQ did not.

Thanks for your help!

**Comment by acogoluegnes** [comment]
Queue deletion or unavailability of the queue master (in case of mirrored queues) can be reasons of consumer cancellation.

It's hard to tell what exactly happened. It's likely the network glitch is not detected as such by the default recovery/retry mechanism, that's why it does not kick in and I suggested to change the default.

More information (server logs, complete stack traces, and versions) could help.

**Comment by xyloman** [comment]
I was able to reproduce something similar where connections remain however, the consumer channel does not restablish on the Rabbit side:

```
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 2020-07-23 14:55:07.950 ERROR 13 --- [ool-7-thread-15] c.r.c.impl.ForgivingExceptionHandler     : Consumer com.rabbitmq.client.impl.recovery.AutorecoveringChannel$2@54c7c062 (com.pivotal.rabbitmq.ReactiveRabbitBuilder$$Lambda$870/0x0000000100707c40@39e9f192#30) method handleCancel for channel AMQChannel(amqp://6d094e67-ecea-4661-87be-d633ddcc9e51@10.156.82.5:5671/ca46e877-c3a4-40a1-a3d5-cca170486b2f,30) threw an exception for channel AMQChannel(amqp://6d094e67-ecea-4661-87be-d633ddcc9e51@10.156.82.5:5671/ca46e877-c3a4-40a1-a3d5-cca170486b2f,30)
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT reactor.core.Exceptions$BubblingException: reactor.rabbitmq.RabbitFluxException: java.io.IOException
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.Exceptions.bubble(Exceptions.java:173) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.Operators.onErrorDropped(Operators.java:635) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:140) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.Mono.subscribe(Mono.java:4204) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4330) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.Mono.subscribe(Mono.java:4190) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.Mono.subscribe(Mono.java:4126) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.Mono.subscribe(Mono.java:4098) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.rabbitmq.Receiver.lambda$consumeManualAck$13(Receiver.java:181) ~[reactor-rabbitmq-1.4.3.RELEASE.jar:1.4.3.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.resubscribe(FluxRepeatPredicate.java:113) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onComplete(FluxRepeatPredicate.java:94) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:146) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.onComplete(FluxTakeUntilOther.java:236) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:438) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:784) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:732) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:239) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxCreate$SerializedSink.drain(FluxCreate.java:205) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.FluxCreate$SerializedSink.complete(FluxCreate.java:196) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.rabbitmq.Receiver.lambda$null$10(Receiver.java:201) ~[reactor-rabbitmq-1.4.3.RELEASE.jar:1.4.3.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel$2.handleCancel(AutorecoveringChannel.java:566) ~[amqp-client-5.9.0.jar:5.9.0]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at com.rabbitmq.client.impl.ConsumerDispatcher$3.run(ConsumerDispatcher.java:115) ~[amqp-client-5.9.0.jar:5.9.0]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104) ~[amqp-client-5.9.0.jar:5.9.0]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT Caused by: reactor.rabbitmq.RabbitFluxException: java.io.IOException
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.rabbitmq.Receiver.lambda$null$12(Receiver.java:228) ~[reactor-rabbitmq-1.4.3.RELEASE.jar:1.4.3.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:168) ~[reactor-core-3.3.7.RELEASE.jar:3.3.7.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	... 31 common frames omitted
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT Caused by: java.io.IOException: null
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129) ~[amqp-client-5.9.0.jar:5.9.0]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125) ~[amqp-client-5.9.0.jar:5.9.0]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at com.rabbitmq.client.impl.ChannelN.basicConsume(ChannelN.java:1384) ~[amqp-client-5.9.0.jar:5.9.0]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicConsume(AutorecoveringChannel.java:532) ~[amqp-client-5.9.0.jar:5.9.0]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicConsume(AutorecoveringChannel.java:492) ~[amqp-client-5.9.0.jar:5.9.0]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	at reactor.rabbitmq.Receiver.lambda$null$12(Receiver.java:206) ~[reactor-rabbitmq-1.4.3.RELEASE.jar:1.4.3.RELEASE]
   2020-07-23T09:55:07.96-0500 [APP/PROC/WEB/0] OUT 	... 32 common frames omitted
```

I was able to reproduce this by performing a rolling restart of the rabbit cluster.  The only way to reestablish the consumer channel is to restart the application.

**Comment by acogoluegnes** [comment]
What kind of queue is it? Depending on the parameters (e.g. durable or not), the queue can be gone after the cluster nodes restart. There can be also subtle failures with auto-delete queues (queues that get deleted once they are no longer consumed from).
