### ISSUE TITLE
Benchmark Test Error

### ISSUE THREAD

**Issue by julang2** [reactor/reactor-rabbitmq#140]
I refer to the docs to use ChannelPool to test, and an error occurred when the number of concurrency exceeded 2. How should this problem be solved?

## Documentation Issue

17:35:29.873 [sender-channel-pool-4826] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException: The mapper returned a null value.
Caused by: java.lang.NullPointerException: The mapper returned a null value.
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:140)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4204)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:124)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
17:35:29.873 [sender-channel-pool-1642] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException: The mapper returned a null value.
Caused by: java.lang.NullPointerException: The mapper returned a null value.
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:140)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4204)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:124)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

## My Rabbitmq Configuration
@Configuration
public class RabbitmqConfig {

  public final static String QUEUE_NAME = "reactive.queue";
  public final static String EXCHANGE_NAME = "reactive.exchange";
  public final static String KEY_NAME = "reactive.key";

  @Resource
  private AmqpAdmin amqpAdmin;

  @Bean
  ConnectionFactory connectionFactory(RabbitProperties rabbitProperties) {
    ConnectionFactory connectionFactory = new ConnectionFactory();
    connectionFactory.useNio();
    connectionFactory.setHost(rabbitProperties.getHost());
    connectionFactory.setPort(rabbitProperties.getPort());
    connectionFactory.setUsername(rabbitProperties.getUsername());
    connectionFactory.setPassword(rabbitProperties.getPassword());
    //return Mono.fromCallable(() -> connectionFactory).cache();
    return connectionFactory;
  }

  @Bean
  Sender sender(ConnectionFactory connectionFactory) {
    SenderOptions senderOptions = new SenderOptions()
        .connectionFactory(connectionFactory)                         // <1>
        .resourceManagementScheduler(Schedulers.boundedElastic());
    return RabbitFlux.createSender(senderOptions);
  }

  @Bean
  ChannelPool channelPool(ConnectionFactory connectionFactory) {
    return ChannelPoolFactory.createChannelPool(         // <1>
        Mono.fromCallable(connectionFactory::newConnection).cache(),
        new ChannelPoolOptions().maxCacheSize(10)                            // <2>
    );
  }

  @Bean
  Receiver receiver(ConnectionFactory connectionFactory) {
    ReceiverOptions receiverOptions = new ReceiverOptions()
        .connectionFactory(connectionFactory)                          // <1>
        .connectionSubscriptionScheduler(Schedulers.boundedElastic()); // <2>
    return RabbitFlux.createReceiver(receiverOptions);
  }

  @Bean
  Flux<Delivery> deliveryFlux(Receiver receiver) {
    return receiver.consumeNoAck(QUEUE_NAME);
  }

  @PostConstruct
  public void declareQueue() {
    amqpAdmin.declareQueue(new Queue(QUEUE_NAME, true, false, true));
    amqpAdmin.declareExchange(new DirectExchange(EXCHANGE_NAME, true, true));
    amqpAdmin.declareBinding(
        new Binding(QUEUE_NAME, DestinationType.QUEUE, EXCHANGE_NAME, KEY_NAME, null));
  }
}

## My API Method
@RestController
@RequestMapping(value = "/rabbitmq/reactive")
public class SendController {

  @Resource
  private Sender sender;

  @Resource
  private ChannelPool channelPool;

  @GetMapping("/sendByChannelPool")
  public Mono<Void> sendByChannelPool(String msg) {
    sender.send(Mono.just(new OutboundMessage(EXCHANGE_NAME, KEY_NAME, msg.getBytes()
    )), new SendOptions().channelPool(channelPool)).subscribe();
    return Mono.empty();
  }
}

## My Benchmark Test
wrk -t10 -c30 -d120s http://192.168.0.132:80/rabbitmq/reactive/sendByChannelPool?msg=ABCDEFGHIJKLMNOPQRSTUVWXYZ123456

**Comment by julang2** [comment]
It works, thanks

**Comment by acogoluegnes** [comment]
Glad to hear it's working, thanks for reporting back.
