### ISSUE TITLE
Sender - Frame enqueuing failed

### ISSUE THREAD

**Issue by pmackowski** [reactor/reactor-rabbitmq#49]
While doing some performance tests, I come across the following error:
```

Caused by: java.io.IOException: Frame enqueuing failed
        at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.sendWriteRequest(SocketChannelFrameHandlerState.java:136)
        at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.write(SocketChannelFrameHandlerState.java:126)
        at com.rabbitmq.client.impl.nio.SocketChannelFrameHandler.writeFrame(SocketChannelFrameHandler.java:88)
        at com.rabbitmq.client.impl.AMQConnection.writeFrame(AMQConnection.java:564)
        at com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:117)
        at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:452)
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:427)
        at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:704)
        at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:679)
        at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:669)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:197)
        at reactor.rabbitmq.Sender.lambda$null$2(Sender.java:126)
        ... 43 common frames omitted
23:36:13.584 [rabbitmq-nio] INFO  c.rabbitmq.client.impl.AMQConnection - Received a frame on an unknown channel, ignoring it
```
It occured for both for `send` and `sendWithPublishConfirms`. 

How to reproduce:
```
import com.rabbitmq.client.Connection;
import org.openjdk.jmh.annotations.*;
import org.openjdk.jmh.infra.Blackhole;
import reactor.core.publisher.Flux;

@BenchmarkMode(Mode.Throughput)
@State(Scope.Benchmark)
@Warmup(iterations = 0)
@Measurement(iterations = 1, time = 5)
@Fork(1)
@Threads(25) // this is important
public class FrameEnqueuingFailedBenchmark {

    Connection connection;
    Sender sender;
    String queue;
    Flux<OutboundMessage> msgFlux;

    @Param({"10000"}) // and this is important
    public int nbMessages;

    @Setup
    public void setupConnection() throws Exception {
        connection = SenderBenchmarkUtils.newConnection();
    }

    @TearDown
    public void closeConnection() throws Exception {
        connection.close();
    }


    @Setup(Level.Iteration)
    public void setupSender() throws Exception {
        queue = SenderBenchmarkUtils.declareQueue(connection);
        sender = RabbitFlux.createSender();
        msgFlux = SenderBenchmarkUtils.outboundMessageFlux(queue, nbMessages);
    }

    @TearDown(Level.Iteration)
    public void tearDownSender() throws Exception {
        SenderBenchmarkUtils.deleteQueue(connection, queue);
        if (sender != null) {
            sender.close();
        }
    }

    @Benchmark
    public void send(Blackhole blackhole) {
        blackhole.consume(sender.send(msgFlux).block());
    }
```

**Comment by pmackowski** [comment]
@acogoluegnes Thank you for explanation. Definitely, I will have to take a closer look at `rabbitmq-java-client`, especially `NioParams`

**Comment by acogoluegnes** [comment]
Yes, the NIO mode is more tweakable (and more capricious) than the blocking mode. I'm closing this one for now, you can re-open it or create another one if necessary.
