### ISSUE TITLE
Send failed

### ISSUE THREAD

**Issue by viartemev** [reactor/reactor-rabbitmq#61]
I tried to compare performance `reactor-rabbitmq` with my solution and can't do it because all the time I get an error.
I use SimpleSender for it. Count of messages is `1_000_000`
```
11:35:00.839 ERRORr.rabbitmq.samples.SampleSender - Send failed
reactor.rabbitmq.RabbitFluxException: Not retryable exception, cannot retry
	at reactor.rabbitmq.ExceptionHandlers$SimpleRetryTemplate.retry(ExceptionHandlers.java:112)
	at reactor.rabbitmq.ExceptionHandlers$RetrySendingExceptionHandler.accept(ExceptionHandlers.java:149)
	at reactor.rabbitmq.ExceptionHandlers$RetrySendingExceptionHandler.accept(ExceptionHandlers.java:137)
	at reactor.rabbitmq.Sender$PublishConfirmSubscriber.onNext(Sender.java:580)
	at reactor.rabbitmq.Sender$PublishConfirmSubscriber.onNext(Sender.java:489)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxRange$RangeSubscription.fastPath(FluxRange.java:129)
	at reactor.core.publisher.FluxRange$RangeSubscription.request(FluxRange.java:107)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:140)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:233)
	at reactor.rabbitmq.Sender$PublishConfirmSubscriber.onSubscribe(Sender.java:559)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.FluxRange.subscribe(FluxRange.java:68)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at reactor.rabbitmq.Sender$PublishConfirmOperator.subscribe(Sender.java:485)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7734)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:184)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1476)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:457)
	at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
	at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
	at reactor.core.publisher.MonoFlatMapMany.subscribe(MonoFlatMapMany.java:49)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7734)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:81)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:179)
	at reactor.core.scheduler.ElasticScheduler$DirectScheduleTask.run(ElasticScheduler.java:291)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Frame enqueuing failed
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.sendWriteRequest(SocketChannelFrameHandlerState.java:136)
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.write(SocketChannelFrameHandlerState.java:126)
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandler.writeFrame(SocketChannelFrameHandler.java:88)
	at com.rabbitmq.client.impl.AMQConnection.writeFrame(AMQConnection.java:564)
	at com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:117)
	at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:452)
	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:427)
	at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:704)
	at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:679)
	at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:669)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:197)
	at reactor.rabbitmq.Sender$PublishConfirmSubscriber.onNext(Sender.java:571)
	... 34 common frames omitted
```
Any ideas how can I fix it?
I think this issue connected with https://github.com/reactor/reactor-rabbitmq/issues/49

**Comment by viartemev** [comment]
Sender fails on average after `150_000` messages.

**Comment by acogoluegnes** [comment]
Yes, same problem as #49, see https://github.com/reactor/reactor-rabbitmq/issues/49#issuecomment-452213716.

Create the `Sender` with `SenderOptions` and a `ConnectionFactory` with appropriate `NioParams`. This is a in the documentation: https://projectreactor.io/docs/rabbitmq/release/reference/#api-guide-sender

E.g.

```java
ConnectionFactory connectionFactory = new ConnectionFactory();
connectionFactory.useNio();
connectionFactory.setNioParams(new NioParams()
  .setWriteQueueCapacity(1_000_000)
  .setWriteEnqueuingTimeoutInMs(60_000);

SenderOptions senderOptions =  new SenderOptions()
    .connectionFactory(connectionFactory);

Sender sender = RabbitFlux.createSender(senderOptions);
```

**Comment by viartemev** [comment]
In general, ConnectionFactory should be created at the start of an application. 
In this case, I don't know how many messages I need to send and parameter `setWriteQueueCapacity` can't be set correctly.
There is a question: How this `setWriteQueueCapacity` will influence on application performance if in general, the application sends only one message at one time, but I some cases it should send `1_000_000`?

**Comment by acogoluegnes** [comment]
This is application and system dependent and "performance" is a very vague term (throughput?, latency?). Here are some of the parameters: the rate of the published messages, their size, the network bandwidth, the load on the broker machine, the topology of the cluster, whether some features like queue mirroring are used. You'll understand it's hard to recommend any value without some proper tests.

Here frames are enqueued in the in-memory queue before being dispatched by the NIO thread. In-memory enqueuing can be very fast (100K or millions of operations per second), whereas network dispatching is typically much slower (a few 10 K of operations per second). The network is overwhelmed and blocks the publisher thread, until the default timeout (10 seconds IIRC) is reached. Note the broker can be overwhelmed as well and block the TCP connection.

You should experiment with the workloads you expect in the application (message throughput and message size typically matter here) and come up with the settings and error handling appropriate to your needs. 

Note:
 * the `writeQueueCapacity` is for outbound *frames*, not messages. A single outbound message is published as 3 or more frames (the method frame, the header and several body frames), depending on the size of the body and the maximum frame size negotiated during the connection opening. 
 * the frames are enqueued in memory with a `LinkedBlockingQueue` by default, but this [can be customized](https://rabbitmq.github.io/rabbitmq-java-client/api/current/com/rabbitmq/client/impl/nio/NioParams.html#setWriteQueueFactory(java.util.function.Function)).

**Comment by asm0dey** [comment]
What should be my settings if I want send-at-any-cost semantics?

**Comment by viartemev** [comment]
@acogoluegnes I need some time to dig into the problem. Could we keep the issue open?

**Comment by acogoluegnes** [comment]
@asm0dey You can increase the queue capacity and the enqueuing timeout. Make sure to deal enqueuing failure though. Publisher confirm can help as well.

**Comment by acogoluegnes** [comment]
@viartemev Sure, no problem.

**Comment by asm0dey** [comment]
@acogoluegnes thanks!

**Comment by pmackowski** [comment]
> * the frames are enqueued in memory with a `LinkedBlockingQueue` by default, but this [can be customized](https://rabbitmq.github.io/rabbitmq-java-client/api/current/com/rabbitmq/client/impl/nio/NioParams.html#setWriteQueueFactory(java.util.function.Function)).

@acogoluegnes It looks like that for `com.rabbitmq:amqp-client:5.6.0` ArrayBlockingQueue is used by default [NioParams#DEFAULT_WRITE_QUEUE_FACTORY](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/nio/NioParams.java#L37) ...

@viartemev You can avoid `java.io.IOException: Frame enqueuing failed` exception with such definition:
```
ConnectionFactory connectionFactory = new ConnectionFactory();
connectionFactory.useNio();
connectionFactory.setNioParams(new NioParams()
       .setWriteQueueFactory(ctx -> new BlockingQueueNioQueue(
               new LinkedBlockingQueue<>(),
               ctx.getNioParams().getWriteEnqueuingTimeoutInMs()
        ))
);
```
Unfortunately, there is other problem with above approach. 
Once all messages (frames) are enqueued in memory and possibly many messages are still not delivered to RabbitMq, channel is being closed and timeouts after 10 seconds with exception:

```
[rabbitmq-sender-connection-subscription-3] WARN  r.r.ChannelCloseHandlers$SenderChannelCloseHandler - Channel 1 didn't close normally: null
[rabbitmq-nio] INFO  c.rabbitmq.client.impl.AMQConnection - Received a frame on an unknown channel, ignoring it
```
but finally all messages are delivered and channel is closed.

**Comment by asm0dey** [comment]
@viartemev It looks like we can add these settings to JMH suite and test on bigger message counts.

@pmackowski thank you for your help, looks awesome!

**Comment by pmackowski** [comment]
You can also mitigate the problem of channel closure timeout with channel pooling introduced in v1.1.0
